### PR TITLE
Session 24

### PR DESCRIPTION
**Pull request by Silmathoron**
PR to add a first version of the informations on session 24 regarding collective behavior and bursting.

### CODE REVIEW

**Review by emptymalei — COMMENTED** [review]
Somehow, the backend for this website, which is called jekyll, can not compile this file. No idea what's happening.

**Comment by emptymalei** [comment]
Do you mind if I make a PDF version of this post and add it as a download? I think jekyll can not process some of the html tags in it or something.

**Comment by Silmathoron** [comment]
Yes, you can do that for now, I'll take the time to complete it and make it without html tags in the coming weeks. I'll do a new PR at that point.

**Comment by emptymalei** [comment]
@Silmathoron I actually found the reason. It's not because of the html tags. Actually it's because of the meta data. Not sure why but I retyped in the meta data, and it works.

```
---
layout: notes
title: "24. From individual neurons to collective bursting"
date: 2016-11-16
author: Tanguy Fardet
summary: Predicting collective dynamics from individual neuron properties.
references: Two dimensional neuron models; Integrate and Fire Models Part 1; Comparison Between Neuron Models; Homogeneous Network; Asynchronous Firing
---
```


And I also changed the path to images. Jekyll actually messed up the path. `assets` should be `../assets`. I know it's weird but that's Jekyll.

Here is the file that works wth jekyll: [24.From_individual_neurons_to_collective_bursting.md.zip](https://github.com/neuronstar/spiking-neuron-models/files/613893/24.From_individual_neurons_to_collective_bursting.md.zip) Eveything else is the same.

**Comment by Silmathoron** [comment]
ok, great!

**Comment by Silmathoron** [comment]
If you don't mind, I'll let you put this preliminary version online and I'll use it as the base to finish it afterwards ;)

**Comment by emptymalei** [comment]
@Silmathoron Sure.

**Comment by emptymalei** [comment]
@Silmathoron It's done.

**Comment by Silmathoron** [comment]
Ok, thanks, I guess you need to update the commit which links the github.io to spiking-neuron-model for it to be visible on the website, right?

**Comment by emptymalei** [comment]
@Silmathoron Well, I can update that website. This is only a submodule of it so just need a commit.

**Comment by emptymalei** [comment]
@Silmathoron It's online now. http://neuronstar.cc/spiking-neuron-models/24.From_individual_neurons_to_collective_bursting/

The only thing, though, is that the avatar is the site default for now. I could change it to your github avatar if you like.

**Comment by Silmathoron** [comment]
Great, thanks.
Don't worry about the avatar, maybe we'll do this once the final version is online...
Thanks again!

**Comment by emptymalei** [comment]
@Silmathoron Cool. No problem.

**Pull request merged**
